### ISSUE TITLE
Test e2e 

### ISSUE THREAD

**Issue by bborlet** [assurance-maladie-digital/starter-kit-vue#62]
Je sais qu'un fichier de conf cypress est présent mais pas d'exemple de tests dans le SK, de plus cypress ne fait pas partie des outils recommandé pour travailler avec nuxt cf https://nuxt.com/docs/getting-started/testing#end-to-end-testing

J'ai déja utilisé [Playwright](https://playwright.dev/)  de mon coté je serais partant pour faire des essaie dessus et pk pas intégré ca au sk par la suite ?

**Comment by DavidFyon** [comment]
Pour les tests cypress : `pnpm test:e2e` ou` pnpm cypress:open`
